domain: k3s.example.com

cluster:
  user: k3s
  password: changme
  usergroup: k3scluster
  token: acb6d54e-6669-4c89-9cd5-b52fa27cd1b5
  noDeploy:
  - local-storage
  nodes:
  - ip: 192.168.0.11
    hostname: k3s-node-1
    role: master
    ssh:
      user: k3s
    raspiGpio: true

  - ip: 192.168.0.12
    hostname: k3s-node-2
    ssh:
      user: k3s
    raspiGpio: true

  - ip: 192.168.0.13
    hostname: k3s-node-3
    ssh:
      user: k3s
    raspiGpio: true

  - ip: 192.168.0.14
    hostname: k3s-node-4
    ssh:
      user: k3s
    raspiGpio: true
